<?php

namespace DG\TicketingBundle\Repository;

/**
 * DurationTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DurationTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
