#Première étape réservation
dg_ticketing_home:    
    path:      /{page}
    defaults:
        _controller:  DGTicketingBundle:Booking:index
        page:        1
    requirements:
        page: \d*
    
dg_ticketing_add:
    path:      /add
    defaults: { _controller: DGTicketingBundle:Booking:add }

#2eme etape
dg_ticketing_ticket:
    path:      /paiement/{id}
    defaults: { _controller: DGTicketingBundle:Booking:paiement }
    requirements:
        id: \d+

#3eme etape
dg_ticketing_terminated:
    path:      /terminated/{id}
    defaults: { _controller: DGTicketingBundle:Booking:terminated }
    requirements:
        id: \d+

#4eme etape
dg_ticketing_mailing:
    path:      /mailling/{id}
    defaults: { _controller: DGTicketingBundle:Booking:mailling }
    requirements:
        id: \d+

# Error  
dg_ticketing_add:
    path:      /error
    defaults: { _controller: DGTicketingBundle:Booking:error }

#Voir une Réservation particulière
dg_ticketing_view:
    path:      /booking/{id}
    defaults: { _controller: DGTicketingBundle:Booking:view }
    requirements:
        id: \d+